#hello
name: Build Windows App

on:
  push:
    branches: [ master ]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller opencv-python moviepy pygame
    - name: Build with PyInstaller
      run: |
        cd Tkinter
        pyinstaller --onedir --windowed tv_time_app.py
    - uses: actions/upload-artifact@v4
      with:
        name: windows-tv-time-app
        path: Tkinter/dist/*